### ISSUE TITLE
Named categorical

### ISSUE THREAD

**Issue by bzinberg** [probcomp/Gen.jl#125]
# It would be nice to have a

categorical distribution whose support is an arbitrary set of values, rather than integers 1 through N.  As @sharlaon points out, this distribution may (we think?) allow us to store deterministic values in the trace without any extra design overhead, by tracing a named categorical draw with singleton support.

The code below is an implementation pasted from [Cora](https://github.com/probcomp/Cora/blob/595fb39b6d80db473f04c82fafb1b83a634f1b5d/src/named_categorical.jl):

```jl
struct NamedCategorical <: Gen.Distribution{Symbol} end

# TODO(https://github.com/probcomp/Gen/issues/110): Remove this once Gen's
# dependency on Distributions.jl is updated
function Gen.Distributions.isprobvec(x::AbstractArray{T}) where T <: Real
  Gen.Distributions.isprobvec(collect(x))
end

"""
    named_categorical(probs::SVector{N, T},
                      labels::SVector{N, Symbol}) where {N, T<:Real}
Sample an element from `labels` according to the probability masses in
`probs`.  Requires `all(probs .>= 0)` and `sum(probs) == 1.0`.
"""
const named_categorical = NamedCategorical()

function Gen.logpdf(::NamedCategorical,
                    label::Symbol,
                    probs::SVector{N, T},
                    labels::SVector{N, Symbol}) where {N, T<:Real}
    d = Gen.Distributions.Categorical(probs)
    i = findfirst(==(label), labels)
    Gen.Distributions.logpdf(d, i)
end

function Gen.logpdf_grad(::NamedCategorical,
                         label::Symbol,
                         probs::SVector{N, T},
                         labels::SVector{N, Symbol}) where {N, T<:Real}
    (nothing, nothing, nothing)
end

function Gen.random(::NamedCategorical,
                    probs::SVector{N, T},
                    labels::SVector{N, Symbol}) where {N, T<:Real}
  labels[rand(Gen.Distributions.Categorical(probs))]
end

(::NamedCategorical)(probs, labels) = Gen.random(NamedCategorical(),
                                                 probs, labels)

Gen.has_output_grad(::NamedCategorical) = false
Gen.has_argument_grads(::NamedCategorical) = (false, false)

# export named_categorical
```

**Comment by bzinberg** [comment]
I guess there would have to be a type parameter, a in `NamedCategorical{T} <: Distribution{T}` (?), whereas the above code fixes `T` to be `Symbol`.

**Comment by alex-lew** [comment]
I've found this useful in PClean, and in Metaprob. 

A couple comments:

1. The `@dist` DSL sitting in a PR now enables this as a one-liner: `@dist named_categorical(names, probs) = names[categorical(probs)]`. You could also potentially do `@dist named_categorical(names, probs) = names[categorical(normalize(probs))]`.
2. There's another version (called `choose_proportionally`) that I've implemented for PClean, with gradients.
3. An important consideration: you don't necessarily want to use `find_first` in logpdf, because there may be repeat names, and the logpdf should take them all into account.
4. Users of such a distribution should be careful that if the names ever change, so must the address: choices with different supports should have different addresses for Gen's inference to be correct.

**Comment by alex-lew** [comment]
> this distribution may (we think?) allow us to store deterministic values in the trace without any extra design overhead, by tracing a named categorical draw with singleton support.

Note that this is not quite the case, due to restriction (4) above. Is there a use case you have in mind for tracing deterministic values? Recall that traces already store return values, so if you just want easy access to some deterministic value, one option is to return it from your function. (I’ve found this pattern very useful — and something missing from Metaprob.)

**Comment by bzinberg** [comment]
Yeah, after seeing your comment I was trying to see if there was some
workaround possible given the design constraint in 4.  Didn't come up with
anything clean.

We do have use cases, and Vikash/Marco/I had some discussion last week that
we'll definitely want to get your input on as well.

**Comment by alex-lew** [comment]
Sounds good :-) I’ve been thinking quite a bit about deterministic values in traces (for MetaGen), so would be curious to discuss when you’re ready.

**Comment by marcoct** [comment]
This was addressed by https://github.com/probcomp/Gen/pull/103
