### ISSUE TITLE
Add a dirichlet distribution!

### ISSUE THREAD

**Issue by serenabooth** [probcomp/Gen.jl#141]
Ankit Shah and I are trying to use Gen to support a project and would love the addition of a dirichlet distribution

**Comment by marcoct** [comment]
Thanks for using Gen! :)

This should be pretty straightforward. Some notes:
- Distributions.jl has a [Dirichlet distribution](https://juliastats.org/Distributions.jl/stable/multivariate/#Distributions.Dirichlet), from which we can use sampling (for `Gen.random`) and logpdf (for `Gen.logpdf`).
- `Gen.logpdf_grad` could support gradient with respect to concentration vector.
- `Gen.logpdf_grad` could also support gradient with respect to the probability vector, although some care would be required when using these gradients, since the output is constrained to the simplex. This is an example of a random choice with a non-standard base measure, and it might make sense to introduce a Simplex data type to make that explicit. (However, making automatic differentiation interact well with custom data types requires more work, and might wait until the AD refactoring mentioned in https://github.com/probcomp/Gen/issues/128.)

**Comment by dpmerrell** [comment]
What do people think about using an unconstrained parameterization?

The unconstrained parameter may be less intuitive, but probably more practical for gradient-based inference techniques.

**Comment by xukai92** [comment]
Sounds like using Distributions.jl together with Bijectors.jl could work.

**Comment by ztangent** [comment]
Looks like someone is doing this in #225!

**Comment by ztangent** [comment]
Finally resolved by PR #495! (I also forgot that two different people took a step at this, thank you both!)

**Comment by ztangent** [comment]
Reopening this because we have not added `dirichlet` to the Gen docs!

**Comment by ztangent** [comment]
Resolved by #522.

**Comment by deoxyribose** [comment]
Hello,

the type declaration was

`struct Dirichlet <: Distribution{Float64} end`

which threw a conversion error when tracing; 
I made a PR which changes it to

`struct Dirichlet <: Distribution{Vector{Float64}} end`

in #524
