### ISSUE TITLE
Track generative function return values in addition to choicemaps

### ISSUE THREAD

**Issue by georgematheos** [probcomp/Gen.jl#150]
Hi,
I've been enjoying using Gen, but have run into an issue that makes it a bit difficult to use for efficient MCMC inference in complex models.

When tracing a random decision, currently one of two things is added to the trace:
- if the random decision comes from a call do a Gen.distribution, the return value from this function call is added to the trace
- if the random decision comes from a generative function call, the trace is extended to have a submap of all the decisions made by that generative function call

However, it is often useful to have access to the actual return value of generative function calls.  For instance, when implementing MCMC proposal distributions, it often makes sense to use the return value of a generative function as part of the state, and reconstructing this value from the generative function choicemap at every iteration of MCMC is very inefficient.

Part of the reason a language like Gen is powerful is that it allows generative functions to act as probability distributions in their own right, but the fact that the return value from these can't be accessed in the trace severely cuts down on this promise in some situations.

I propose that the trace for a generative function should both track the submaps for generative function calls and the return values from these.  Here is an example of how this could look:

Say I declare the following gen functions:
```julia
@gen function gen_val_inner()
  val = @trace(uniform_discrete(0, 10), :val_inner)
  val * 2
end

@gen function gen_val_outer()
  val = @trace(gen_val_inner(), :val_outer)
  val * 5
end

trace = Gen.simulate(gen_val_outer, ())
```

Currently, the choicemap for this trace only has one key in it, namely, `:val_outer => :val_inner`.  This contains the choice made in the `uniform_discrete` call.  Say for the sake of discussion that this val ended up being `3` (ie. `trace[:val_outer => :val_inner] == 3`).

This means that the function `gen_val_inner` returned the value 6.  In this case it is trivial to calculate that it returned this; however, in many cases a generative function will manipulate the probability-distribution-level decision in complicated ways that are computationally expensive to simulate.  It would be useful to not have to recalculate this when doing MCMC proposals from the trace, and instead have access to the value returned by `gen_val_inner` from the trace.

I propose that we should both be able to access `trace[:val_outer => :val_inner] == 3` and `trace[:val_outer] == 6`.  Ie. if we index into the trace (/choicemap the trace wraps) with a top-level address, it should return the value returned by the generative function itself, rather than just being an anchor into a choicemap for this generative function.

**Comment by fsaad** [comment]
@georgematheos Thanks for using Gen!

You should be able to obtain the return value of any call to a generative function by using `Gen.get_retval(trace)`: https://probcomp.github.io/Gen/dev/ref/gfi/#Gen.get_retval.  Does that address the functionality you are looking for?

Edit: I see, you need the return value from a nested function call.  I'm not sure whether this is currently possible but will check the docs (there might be a way to call `get_retval` by extracting an appropriate subtrace).

**Comment by fsaad** [comment]
@georgematheos Building on your example, I think the following code:

```julia
@gen function gen_val_inner()
  val = @trace(uniform_discrete(0, 10), :val_inner)
  val * 2
end

@gen function gen_val_outer()
  val = @trace(gen_val_inner(), :val_outer)
  val * 5
end

trace = Gen.simulate(gen_val_outer, ())
retval_outer = get_retval(trace)

subtrace = Gen.get_call(trace, :val_outer).subtrace
retval_inner = Gen.get_retval(subtrace)
```

That said, I do not believe that `Gen.get_call` is formally of the trcae API. @marcoct Can weigh in further...

**Comment by marcoct** [comment]
@georgematheos Thanks for the detailed feedback!

Currently, the only state that is accessible through the GFI (besides various scores and weights and arguments to the function) is (1) the choice map, and (2) as @fsaad mentioned, the return value of the top-level generative function call is available with `get_retval(trace)`. We have been using the return value of the top-level function as a place to store the type of state you're talking about, so storing whatever additional state the proposal needs in the return value of the top-level generative function is what I would recommend in the very short term, e.g.:

```julia
@gen function gen_val_inner()
  val = @trace(uniform_discrete(0, 10), :val_inner)
  return val * 2
end

@gen function gen_val_outer()
  val = @trace(gen_val_inner(), :val_outer)
  return (val * 5, val)
end

trace = Gen.simulate(gen_val_outer, ())
(val_times_5, val) = get_retval(trace)
```
This is suboptimal if you're writing a proposal that is essentially local to the inner function call, but you need to pass data up to the top-level return value just so it can be read by the proposal using `get_retval`. @georgematheos Do you have a specific example of model, and the corresponding proposal you'd like to write for it? I wonder whether the `get_retval` approach would be doable.

In the medium term, we've been planning to add more support for addressable auxiliary state to the generative function interface. Storing the return value of calls under the their call address as you're suggesting is a good example of this. I think it's definitely reasonable for the built-in modeling languages (i.e. `@gen function`s) to write the return value of each inner function call to this auxiliary state, addressed by the hierarchical `@trace` address of the call, as you're suggesting. We've also discussed allowing `@gen function`s to store additional auxiliary state at arbitrary addresses, but I think just storing return values of function calls is a good first step.

But I don't think that all generative functions (i.e. those not written using the built-in modeling languages) should be required to expose their function call structure. In particular, custom user-defined generative functions should be able to can write to arbitrary (hierarchical) addresses without having any notion of internal function calls.

So here's a concrete proposal to address this:

- `get_choices(trace)` will still return the choice map, and will not include any auxiliary state (e.g. no return values of inner generative function calls, just distribution calls). Generative functions can be used in contexts where you need only the random choices (e.g. when a generative function is used as a proposal distribution), so it needs to still be possible to extract the choices separately, which `get_choices` provides.

- Both the auxiliary state and the choices will be accessible using `Base.getindex(trace)`, just like choices (e.g. `trace[addr]`). This means, you cannot store auxiliary state at the address of a random choice, because the addresses will collide. I think that's fine. The GFI will be extended slightly to document that `Base.getindex` can give auxiliary addressable state, in addition to random choices. But generative functions will not be required to populate any auxiliary state. Custom generative functions can write auxiliary state to arbitrary addresses, as long as they don't collide with random choice addresses.

- The dynamic modeling language and static modeling language will store the return value of each call in the trace (they already do this), and will make these accessible as auxiliary state through `Base.getindex(trace)`.

- Note that although auxiliary state will use the same address hierarchy as random choices, it will not be constrainable (e.g. you will not be able to construct a choice map containing this state and pass it to `generate`).

I think would actually be very straightforward to add this in a backward compatible way.

P.S. Also, to add some context around the question of maintaining state, I'll distinguish between (i) the state that an implementation of the GFI has access to and (ii) the state that the caller of the GFI (e.g. a Gen inference program) has. A custom generative function can have a custom trace type that stores arbitrary state in addition to the choice map. But I know you're asking about (ii) in the context of the built-in modeling languages, not custom generative functions or new modeling languages.

**Comment by marcoct** [comment]
This PR partially implements the above proposal: https://github.com/probcomp/Gen/pull/153.

```julia
using Gen 

@gen function gen_val_inner()
  val = @trace(uniform_discrete(0, 10), :val_inner)
  val * 2 
end

@gen function gen_val_outer()
  val = @trace(gen_val_inner(), :val_outer)
  val * 5 
end

trace = Gen.simulate(gen_val_outer, ()) 

@assert trace[:val_outer] == 2 * trace[:val_outer => :val_inner]
```

The PR does not implement this behavior for the static modeling language (only the dynamic modeling language), but that should also be fairly straightforward.

**Comment by bzinberg** [comment]
1. @marcoct,
> We've also discussed allowing @gen functions to store additional auxiliary state at arbitrary addresses, but I think just storing return values of function calls is a good first step.

Aren't the two basically equivalent, as one can tag an arbitrary intermediate value by wrapping it in a traced call to the identity generative function?

2. Is my understanding correct that within the GFI, the semantics of the proposed aux state are the same as choice maps except that one can't constrain them using `Gen.generate`?

3. When you, Vikash and I talked a few months ago about the possibility of storing and exposing deterministic values (aux state) within a trace, you had some concerns about what contract consumers of that state would have to follow in order to avoid introducing conceptual bugs into the system (I think along the lines that an overly reflective API would break some of the desired probabilistic semantics).  Are these concerns still present, or have you given more thought to them, or do they not apply to this particular extension?

**Comment by marcoct** [comment]
> Aren't the two basically equivalent, as one can tag an arbitrary intermediate value by wrapping it in a traced call to the identity generative function?

Good point. For the case when you allow arbitrary writes to the auxiliary state, I was imagining that some special syntax for recording to auxiliary state would be introduced, whereas this PR doesn't introduce any new syntax because it only records function return values. It would be possible to add some syntactic sugar on top of this PR to support arbitrary writes, although generating lots of subtraces would introduce unnecessary overhead, so that would not be a very optimized implementation approach. I prefer seeing how much the limited version of the feature implemented in this very lightweight PR helps us before committing to introducing the more complex variants of this feature that would introduce new syntax and larger implementation.

> Is my understanding correct that within the GFI, the semantics of the proposed aux state are the same as choice maps except that one can't constrain them using Gen.generate?

I wouldn't put it that way. The 'core' semantics of a generative function is still a tuple of (i) a probability distribution on choice maps, and (ii) function from choice maps and arguments to return value. The auxiliary state doesn't change these core semantics. I guess you could formalize the auxiliary state as an indexed collection of deterministic functions that are kind of like the return value function (mapping choice maps and arguments to a value).

> When you, Vikash and I talked a few months ago about the possibility of storing and exposing deterministic values (aux state) within a trace, you had some concerns about what contract consumers of that state would have to follow in order to avoid introducing conceptual bugs into the system (I think along the lines that an overly reflective API would break some of the desired probabilistic semantics). Are these concerns still present, or have you given more thought to them, or do they not apply to this particular extension?

I think they do not apply to this particular extension. I think the biggest conceptual issues are introduced when you try to allow functions written in the built-in modeling languages to **read from** the auxiliary state themselves. That is something @vkmvkmvkmvkm and I had discussed a while back that introduces a lot of additional complexity into the modeling language semantics and implementation. The PR here doesn't allow generative functions to read from the auxiliary state, which is a much simpler feature that is useful by itself.

**Comment by georgematheos** [comment]
Thanks for the quick and detailed responses!

@fsaad I was not aware of the `Gen.get_call` function;  I don't think this is in the official API but it is good to be aware of.  Looks like it could certainly be used with `get_retval` in the short term to get the functionality I'm looking for.

@marcoct I think the PR looks like it does exactly what I had in mind, at least for the dynamic modeling language.  I think the approach of having more of a distinction between indexing into traces vs choicemaps makes sense, since this allows the "pure" choicemaps as before which do not contain any auxiliary state, while also allowing users to access the full trace for inner generative functions.

Until this is pushed, for what I'm doing, bubbling the return all the way to the outermost generative function would be a bit inelegant (though not too bad; maybe I will do it).  I think another workaround I could use is to implement what should conceptually be a generative function as a Gen probability distribution instead.  The application I'm working on will need custom MH proposals for parts of the inference to run efficiently, so I have already hand-derived these distributions in closed form, so it isn't essential in this case to have it as a generative function that the built-in Gen inference can work on (this will be too slow anyway).

The research I'm doing (@ Berkeley) involves probabilistic first-order inference, along the lines of what BLOG is designed for.  (I might switch to BLOG at some point, but it's easier to extend Gen in the ways I'm needing for now at least.)  It would be very cool to port the core of the BLOG inference engine to Gen in the form of a specific generative function type for first-order models, though this would be a pretty big undertaking.  (Maybe if I have time this summer I'll look into it :).)  It would extend the power of Gen a lot to have this built-in, though, so as a longer-term time investment this is probably worth thinking about.

[I understand how to proceed with my work at this point, so feel free to close the issue; might also make sense to leave open until the PR has been pushed / another PR implementing similar functionality for static functions has been added.]

**Comment by marcoct** [comment]
> I think another workaround I could use is to implement what should conceptually be a generative function as a Gen probability distribution instead. The application I'm working on will need custom MH proposals for parts of the inference to run efficiently, so I have already hand-derived these distributions in closed form, so it isn't essential in this case to have it as a generative function that the built-in Gen inference can work on (this will be too slow anyway).

Okay -- it would be interesting to see the performance difference between a Gen implementation and a hand-coded one. If you want, we can also discuss different implementation strategies in Gen some time.

> The research I'm doing (@ Berkeley) involves probabilistic first-order inference, along the lines of what BLOG is designed for. (I might switch to BLOG at some point, but it's easier to extend Gen in the ways I'm needing for now at least.) It would be very cool to port the core of the BLOG inference engine to Gen in the form of a specific generative function type for first-order models, though this would be a pretty big undertaking. (Maybe if I have time this summer I'll look into it :).) It would extend the power of Gen a lot to have this built-in, though, so as a longer-term time investment this is probably worth thinking about.

That sounds really interesting. I agree that implementing a generative function type that's backed by part of the BLOG inference engine would be very cool. I'd love to hear more some time about your use case.

P.S. If you want to just chat about Gen in another forum some time -- there is a Gen channel in the Julia Slack (https://slackinvite.julialang.org/).

**Comment by georgematheos** [comment]
Thanks for the link to the slack; I'll certainly join!

The reason I'm using a hand-coded proposal here is that the built-in Gen proposals for MH have a very low acceptance probability in my use case, since a lot of early decisions cause future evidence decisions to have 0 probability of occurring.  I think this is something BLOG handles a bit better since in a language constrained by first-order semantics, it is possible to reason about this downstream behavior.

The hand-coded proposal is also useful since it lets me "integrate" over some variables which are drawn from conjugate priors.  When doing these updates, since there are conjugate priors involved, the proposal distribution is based on the counts of certain decisions; it is much more efficient to track the counts in a data structure than to have the proposal generative function count the decisions from the Gen trace each time it performs an update.  This is why I want this "auxiliary state", to track things like this count.  That said, I realize I can just construct the state once and then keep track of it in the inference code, so it isn't essential to have it stored in the trace (though it is sort of nice to do this). 
 Another thing I can do to keep this state in the trace is implement an "identity" probability distribution and then do `@trace(identity(counts_structure), :counts_structure)` in the generative function.


@marcoct I'd love to hear from you if you have any advice about ways I could better better structure my Gen code to reason about downstream decisions and improve the MH acceptance probabilities; I'd also be happy to discuss possibly implementing more BLOG-like inference for Gen.  I'll send you a slack message.

**Comment by bzinberg** [comment]
> I think the biggest conceptual issues are introduced when you try to allow functions written in the built-in modeling languages to **read from** the auxiliary state themselves. That is something @vkmvkmvkmvkm and I had discussed a while back that introduces a lot of additional complexity into the modeling language semantics and implementation.

I see -- so while the GFI doesn't actually forbid this (and kind of can't -- the GFI doesn't even require generative functions to have source code), the built-in modelling language does intentionally forbid it.  (I can imagine why -- tracing an expression that itself reads from the choicemap could complicate things.)  That clarifies things a bunch for me, thanks.

**Comment by marcoct** [comment]
> I see -- so while the GFI doesn't actually forbid this (and kind of can't -- the GFI doesn't even require generative functions to have source code), the built-in modelling language does intentionally forbid it. (I can imagine why -- tracing an expression that itself reads from the choicemap could complicate things.) That clarifies things a bunch for me, thanks.

Exactly -- the GFI doesn't prevent you from implement whatever modeling language features you want, including e.g. special syntax for code that only runs in certain contexts (i.e. when updating an existing trace).

**Comment by georgematheos** [comment]
Closing this since the "aux state" pull requests fix the title issue.
