### ISSUE TITLE
Static trace indexing very slow due to runtime value type dispatch

### ISSUE THREAD

**Issue by georgematheos** [probcomp/Gen.jl#173]
I have been spending some time profiling Gen inference code, and one thing I've found is that `getindex` calls for static traces (/static choicemaps) are extremely slow.  After poking around for a bit, I have come to believe this is because the current mechanism used for indexing relies on Julia type dispatch, but due to shortcomings in the Julia compiler, it is unable to do this dispatch at compile time.

Here's an example of a little test I have run:
```julia
using Gen

@gen (static) function static()
    a = @trace(normal(0, 1), :a)
end
Gen.load_generated_functions()

@gen function dynamic()
    return @trace(normal(0, 1), :a)
end

function many_lookups(tr)
    for _=1:1e5
        x = tr[:a]
    end
end

println("dynamic:")
dynamic_tr = simulate(dynamic, ())
@time many_lookups(dynamic_tr)

println("static:")
static_tr = simulate(static, ())
@time many_lookups(static_tr)
```
This yields output:
```
dynamic:
  0.085845 seconds (402.20 k allocations: 18.410 MiB)
static:
  1.271537 seconds (419.16 k allocations: 19.311 MiB, 0.97% gc time)
```
The dynamic lookups run about 15x faster than the static ones.

Profiling the static lookup (after JIT compilation has run):
```
25218 ...erformance/trace_lookup2.jl:15; many_lookups(::Main.TraceLookup2.var"##Sta...
 25216 ...pqN/src/static_ir/trace.jl:40; getindex
  25187 ...en/VlpqN/src/choice_map.jl:75; getindex
   25184 ...pqN/src/static_ir/trace.jl:18; get_value(::Gen.StaticIRTraceAssmt{Main....
    24812 ./essentials.jl:695; Val(::Symbol)
    201   ./none:0; static_get_value
     201 ./Base.jl:20; getproperty
```
The way the static lookups currently works is that to lookup `addr`, we create `Val{addr}` and then call `static_get_value(choices, Val(addr))`.  The profiler shows that most of the time is spent right after we just wrapped the symbol in a `Val`, which I'm interpreting to mean that most of the time is spent with julia searching for the proper method of `static_get_value` for the given `Val{:a}` type.  In other words, this method dispatch is happening at runtime, not compile-time.

This is a bit ironic in my view, because the whole reason to use value dispatch for static lookups is to speed things up by doing as much work at compile time as possible!  Ie. what we want to have happen is that when we call `ch = get_choices(tr); ch[:a]`, Julia should at compile time realize:
1. this is equivalent to `static_get_value(ch, Val(:a))`
2. this is then equivalent to `ch.FIELDNAME` where FIELDNAME is the gensym-generated fieldname in the static trace which stores the given value.  (this is encoded in the code created in `generate_static_get_value` in `Gen/src/static_ir/trace.jl`.

Then, wherever we type `ch[:a]`, it would be compiled to `ch.FIELDNAME`.  For addresses which are pairs rather than raw values, it would be a bit more involved, but ideally the Julia compiler would inline things nicely so that the top-level lookup is direct.

Unfortunately, this isn’t happening.  My initial hope was that using the `@inline` macro would fix it, and while it helps performance a lot, it doesn't do 100% of what we want.  When I added a bunch of `@inline` macros throughout the `Gen/src/static_ir/trace.jl` and `Gen/src/choice_map.jl` files to more or less all the methods for static choicemap lookups.  This makes the `many_lookup` function run as fast as for the dynamic trace: `0.080498 seconds (319.08 k allocations: 17.801 MiB)`.

This in and of itself is a huge improvement, and is certainly worth implementing, but I’m still not totally satisfied with it.  When I run `@code_typed ch[:a]` to see what low-level representation Julia is compiling into, I get the following:

```
CodeInfo(
1 ─ %1 = invoke Main.TraceLookup2.Gen.Val(_3::Symbol)::Val{_A} where _A
│   %2 = (isa)(%1, Val{:a})::Bool
└──      goto #3 if not %2
2 ─ %4 = Base.getfield(choices, :trace)::Main.TraceLookup2.var"##StaticIRTrace_static#1095"
│   %5 = Base.getfield(%4, Symbol("##choice_value#1063_a"))::Float64
└──      goto #4
3 ─ %7 = Main.TraceLookup2.Gen.static_get_value(choices, %1)::Float64
└──      goto #4
4 ┄ %9 = φ (#2 => %5, #3 => %7)::Float64
└──      goto #5
5 ─      return %9
) => Float64
```
It looks like the value dispatch is happening in this runtime code!  [*UPDATE:* I made a julia issue about this and it turns out inlining _does_ actually work exactly as I was hoping. The code above looks wrong due to the way I am using `@code_typed`.  See the below comment.  I will include the rest of the discussion I'd put here anyway, but looks like inlining is sufficient, at least in the case where addresses are not hierarchical.]

So the inlining is improving performance some way other than moving the dispatch to compile time.  (This suggests to me that maybe other places in Gen could benefit from inlining, especially since there is a lot of "passing values through" combinators, etc., that happens.  I'll take a look at this once I get a chance.)

If instead I run `@code_typed static_get_value(ch, Val(:a))`, we get
```
CodeInfo(
1 ─ %1 = Base.getfield(choices, :trace)::Main.TraceLookup2.var"##StaticIRTrace_static#1133"
│   %2 = Base.getfield(%1, Symbol("##choice_value#1101_a"))::Float64
└──      return %2
) => Float64
```
We see here no logic for dispatch is included in the compiled code; all the logic has been figured out already.  This is what we want.

While it seems that the Julia compiler should be able to figure out this optimization, but apparently it can’t, as is noted here: https://discourse.julialang.org/t/value-type-dispatch-on-constants/858. This is pretty old, but looks like it hasn’t been resolved; probably we should create an issue on the Julia repository so they can implement this optimization.

***

In terms of “fixing” this, my sense is that it might be best to move away from the julia value-type multiple dispatch altogether, at least until this optimization is added to the Julia compiler.  One idea is that we could simply use deterministic field names for static traces rather than using `gensym` to create symbols.  To illustrate what I mean by this:

Say we have the gen function
```
@gen (static) function foo()
	a = @trace(normal(0, 1), :a)
	b = @trace(normal(0, 1), :b)
	return a + b
end
```
Currently a trace struct is generated that looks something like this:
```
struct FooTrace
#valueof#a#generatedsymbol
#valueof#b#generatedsymbol
…[other stuff]…
end
```
where the fields `#valueof#a#generatedsymbol` and `#valueof#b#generatedsymbol` store the values for the static IR nodes generated due to the `@trace`s in the generative function.  These symbols are generated with `gensym`, so there is no easy way to know what these will be at runtime.  We then generate code that looks like this to get access to the values:

```
function static_get_value(choices::StaticChoiceMap, ::Val{:a})
	return choices.trace.#valueof#a#generatedsymbol
end
```
ie. we rely on multiple dispatch to map from the address symbol (`:a`) to the trace symbol (`#valueof#a#generatedsymbol`).

It seems to me that it would be reasonable to just make the trace fieldnames deterministic w.r.t. the addresses, rather than using `gensym`.  In other words, we could just have our struct look like

```
struct FooTrace
valof_a
valof_b
…[other stuff]…
end
```
And then have our `get_value` be something like
```
function static_get_value(choices::StaticChoiceMap, addr)
	value_fieldname = Symbol(“valof_$addr”)
	return getproperty(choices.trace, value_fieldname)
end
```

I’ll take a look at this once I have a chance and see if I can get an implementation of it working.  (Might do a bit more code profiling first to see where some other performance bottlenecks are.)  If there's some reason we need the static trace fieldnames to be created by `gensym` that I haven’t understood, or if there's anything else I'm misunderstanding about the code, please let me know.  Thanks!

**Comment by georgematheos** [comment]
Update: made a Julia issue about this (JuliaLang/julia#34220), and discovered that in fact `@inline` *does* work the way we want it to, but due to the mechanics of how `@code_typed` and `@code_llvm` work, to properly see the compiled code, we need to do `f(tr) = tr[:a]; @code_typed f(tr)` rather than just `@code_typed tr[:a]`.

This means that scattering `@inline`s throughout the static choicemap indexing code should be sufficient to fix some of these performance issues.  That said, for hierarchical addressing, I'm not sure it will be enough; I will run some tests on this.  If there are still performance issues for hierarchical addresses, it might still be worth moving the static traces to address-deterministic field-names.

**Comment by marcoct** [comment]
Thanks for surfacing (and addressing!) this. It's closely related to some design aims and challenges regarding performance of the SML.

To provide some context, the design aim of the static modeling language (SML) is to be a modeling language that is easy to analyze statically, to enable generation of faster code specialized to both the model in question and how it is actually used at runtime. This includes generation of a trace data type specialized to the model (generated once when the model is defined), and JIT-generation of specialized code (generated via Julia's generated functions feature).

A challenge is that to exploit the opportunity for specialization, we also need to know something at JIT compile-time about how the model is being used. This includes (i) the addresses we may be reading from the choice map that wraps the model's trace, (ii) the addresses we may be constraining during a call to `update` or `generate`, and (iii) e.g. addresses we may have selected during a call to `regenerate`.

If these addresses / selections are generated dynamically such that they can't be statically inferred (i.e. such that they are not contained in the type information used for JIT code generation) then some of the benefits of the SML (i.e. the potentially faster single-instruction reads from the trace due to using a customized `struct` instead of a hash map) don't occur and can even result in worse performance relative to the dynamic modeling language (DML) as this issue mentions. (Some of the other benefits potentially better asymptotic scaling due to incremental computation, still do occur).

This is not documented, but `ChoiceMap`s (relevant for (ii)) and `Selection`s (relevant for (iii)) have an `AddressSchema` that is associated with their type. For `ChoiceMap`s constructed with `choicemap()` or obtained from the traces of DML functions, and for `Selection`s constructed with `select()`, the address schema is simply the singleton `DynamicAddressSchema`, indicating that no information is known statically about the addresses involved. But `ChoiceMap`s obtained from the traces of SML functions or constructed with `StaticChoiceMap` have a `StaticAddressSchema` that contains a set of (Symbol) addresses that the choice map must have. Similarly for `StaticSelection`s.

The SML code generators can specialize to the static address schemas and generate fast lookups into e.g. the constraint choice map. For example, suppose we are trying to do importance sampling or MH with a custom proposal. If we implement both our model and our proposal as SML functions, then the choice map produced by the proposal will (statically, accessible from its type alone) have a `StaticAddressSchema` that indicates what the proposed addresses were. The code in `generate` or `update` that reads values from these choice maps will call the `static_get_value` function, which should result in a single-instruction lookup in the proposal function's `struct` trace.

For inference programs that mix SML and DML functions, or that use `choicemap()` or `select()` these benefits don't happen. Also `getindex(trace, ..)` for SML functions doesn't currently support any static inference (although it looks like some is possible with `@inline`). Also, for SML and DML functions to be fully interoperable, when the SML GFI implementations get a choice map or selection with a `DynamicAddressSchema`, they actually convert it into one with a `StaticAddressSchema`, and then run their regular code generators. So there is probably some overhead there.

Here is an example showing difference in performance for MH in different cases:

```julia
using Gen

@gen function p()
    x = @trace(normal(0, 1), :x)
    y = @trace(normal(x, 0.1), :y)
end

@gen function q(trace, y::Float64)
    x = @trace(normal(y, 1), :x)
end

@gen (static) function p_static()
    x = @trace(normal(0, 1), :x)
    y = @trace(normal(x, 0.1), :y)
end

@gen (static) function q_static(trace, y::Float64)
    x = @trace(normal(y, 1), :x)
end

Gen.load_generated_functions()

# DML model with DML proposal
function do_inference()
    trace, = generate(p, (), choicemap((:y, 2)))
    for i=1:1000
        trace, = mh(trace, q, (2.,))
    end
    trace
end

# SML model with SML proposal
function do_inference_static()
    trace, = generate(p_static, (), choicemap((:y, 2)))
    for i=1:1000
        trace, = mh(trace, q_static, (2,))
    end
    trace
end

# SML model with DML proposal
function do_inference_mixed()
    trace, = generate(p_static, (), choicemap((:y, 2)))
    for i=1:1000
        trace, = mh(trace, q, (2,))
    end
    trace
end

@time do_inference()
@time do_inference()
@time do_inference()

@time do_inference_static()
@time do_inference_static()
@time do_inference_static()

@time do_inference_mixed()
@time do_inference_mixed()
@time do_inference_mixed()
```

Here are the timing results (note that the first run includes the compile time):

DML/DML
  0.964294 seconds (2.04 M allocations: 107.590 MiB, 2.72% gc time)
  0.011668 seconds (107.16 k allocations: 7.879 MiB, 43.75% gc time)
  0.005369 seconds (107.16 k allocations: 7.879 MiB)

SML/SML
  1.518793 seconds (3.31 M allocations: 170.152 MiB, 2.45% gc time)
  0.001020 seconds (37.03 k allocations: 814.859 KiB)
  0.001112 seconds (37.03 k allocations: 814.859 KiB)

SML/DML
  0.147472 seconds (300.82 k allocations: 16.182 MiB)
  0.010969 seconds (105.03 k allocations: 5.618 MiB, 41.40% gc time)
  0.008622 seconds (105.03 k allocations: 5.618 MiB)

> This means that scattering `@inline`s throughout the static choicemap indexing code should be sufficient to fix some of these performance issues.

I didn't know about the optimization you found in https://github.com/JuliaLang/julia/issues/34220 existed. That's great!

> That said, for hierarchical addressing, I'm not sure it will be enough; I will run some tests on this.

Yeah. I think this is fundamentally a problem of static analysis of inference programs, which can be structured in ways that make addresses completely dynamic. One route towards making the most out of Julia's JIT is to structure inference programs so that the address schemas of all choice maps and selections used with SML functions are static. For example, you can manually construct a `Selection` for use with `mh` by building it up with `StaticSelection`s. However, this is not super ergonomic relative to the simple `choicemap()` and `select()` constructors. This is a potential area for re-design.

> If there are still performance issues for hierarchical addresses, it might still be worth moving the static traces to address-deterministic field-names.

IIRC the names do not need to be gensyms for any good reason. But I'm not sure this is the fundamental issue.  Maybe I'll need to think more about this (I'm not sure I understand how `get_property` works).

**Comment by georgematheos** [comment]
This all sounds great.  I've been looking through the code and I think the design of the static language is quite clever and as you say should allow for some very efficient inference much of the time.  I just opened a little issue (#178) with an idea in mind for how to deal with the fact that it is slow to convert explicit calls to `select()` or `choicemap()` to static selections/choicemaps.

Other than from this conversion of dynamic to static selections, most of the slowdown I've been running into is due to the use of the `Map` combinator.  Ie. in my profiling, I have had something along the lines of:
```julia
@gen (static) function inner()
  # do some stuff
end
@gen (static) function outer()
  # do some stuff
  x = @trace(Map(inner)(...))
  # do some stuff with x
end
```
Before the PR I made, all the static lookups for `inner` were very slow since the type information couldn't pass through the `Vector` trace type at JIT compile time; I think I have fixed this now.  Still, I'm finding that about 3/5 or 4/5 of the time running `update` on `outer` is spent in the `Map` combinator update function.  I think this is because there are all the optimizations you mentioned above for the static trace type make it quite fast to run updates on it.  This makes me wonder if there is some way we could "compile" specific Map update calls in a similar way to how we "compile" different static updates for different choicemap schemas.

For instance, a Map update where the choicemap has 1 value and all argdiffs are `NoChange` should require very little overhead; same with an update where we have an argdiff for exactly 1 of the subtraces, and the choicemap has no constraints.  Perhaps it would make sense to just write a specific method for these situations, but I wonder if we could somehow compile it in general.  Ie. could we have "static" combinators?  What if each `update` call for a "static Map combinator" could generate code which is explicitly inserted into the static modeling language's `update` call so we don't have the overhead of calling different methods and packing/unpacking argdiffs?

Another concern I have is that possibly the `update` function is trying to do too much at once; for example many `update` calls won't need the `discard` output, so spending time constructing it is unnecessary.  Also, sometimes we might want to get the `weight` without needing to construct the whole new trace (eg. when calculating gibbs update probabilities).  Perhaps it would be better to make the GFI a little bigger but even more modular, or have kwargs we can send into the `update` function telling it not to construct certain outputs.

[I'll close this issue once #177 is pushed.]
