### ISSUE TITLE
SMC without rejuvenations fails to perform as well as Importance Sampling 

### ISSUE THREAD

**Issue by sharanry** [probcomp/Gen.jl#291]
SMC without rejuvenation when given all the observations at once is equivalent to Importance Sampling(IS). However, it fails to give similar quality samples as (IS). By the end of the particle steps there seem to be very few (often 1or 2) unique particles left.

[Here](https://gist.github.com/sharanry/e12df9b51412e527e4ea2d4d5866f67c) is a minimal example demonstrating the described problem for a Normal model with unknown parameters.

@marcoct

**Comment by marcoct** [comment]
@sharanry I took another look at this minimal example. I actually think the results you're seeing are not surprising. The importance sampling algorithm is sampling a different 100-particle importance set, then weighing them, and sampling one, and repeating that process 1000 times. The SMC algorithm is sampling a single 1000-particle set, weighing them, and then sampling 100 particles in proportion to the weights. so the IS algorithm is using roughly 100 times more computation and it is going to have much more diversity in its output particles.

A fairer comparison would be to (i) compare the SMC code against this code that uses `Gen.importance_sampling` instead of `Gen.importance_resampling`, and (ii) use e.g. a 1000-particle set in both cases and a 100 sample set in both cases:
```
(traces, log_normalized_weights, log_ml_estimate) = Gen.importance_sampling(model, (N,), obs, 1000)
resampled_traces = [traces[categorical(exp.(log_normalized_weights))] for i in 1:100]
```
Then, these two pieces of code should behave identically.

Separately, the `particle_steps` loop is actually a no-op in the SMC code.

**Comment by marcoct** [comment]
Also, this points to the need for better documentation of importance_sampling, importance_resampling, particle_filter_step!, and probably a version of importance_resampling that resamples num_samples particles all at once. The current importance_resampling function only samples a single output sample from the collection -- this is non-standard, but allows a simple constant-memory implementation. The docs should clarify this.

**Comment by sharanry** [comment]
>A fairer comparison would be to (i) compare the SMC code against this code that uses Gen.importance_sampling instead of Gen.importance_resampling, and (ii) use e.g. a 1000-particle set in both cases and a 100 sample set in both cases:

Thanks a ton for this! This is helped me understand the parallels between implementations of SMC and IS.
