### ISSUE TITLE
Issues with installation instruction on web-site

### ISSUE THREAD

**Issue by nick-torenvliet** [probcomp/Gen.jl#327]
using Gen

```julia
@gen function generate_datum(x, prob_outlier, noise, (grad)(slope),
        (grad)(intercept))::Float64
    if @trace(bernoulli(prob_outlier), :is_outlier)
        (mu, std) = (0., 10.)
    else
        (mu, std) = (x * slope + intercept, noise)
    end
    return @trace(normal(mu, std), :y)
end

function my_inference_program(xs::Vector{Float64}, ys::Vector{Float64}, num_iters::Int)
    # Create a set of constraints fixing the
    # y coordinates to the observed y values
    constraints = choicemap()
    for (i, y) in enumerate(ys)
        constraints["y-$i"] = y
    end

    # Run the model, constrained by `constraints`,
    # to get an initial execution trace
    (trace, _) = generate(my_model, (xs,), constraints)

    # Iteratively update the slope then the intercept,
    # using Gen's metropolis_hastings operator.
    for iter=1:num_iters
        (trace, _) = metropolis_hastings(trace, select(:slope))
        (trace, _) = metropolis_hastings(trace, select(:intercept))
    end

    # From the final trace, read out the slope and
    # the intercept.
    choices = get_choices(trace)
    return (choices[:slope], choices[:intercept])
end

xs = [1., 2., 3., 4., 5., 6., 7., 8., 9., 10.]
ys = [8.23, 5.87, 3.99, 2.59, 0.23, -0.66, -3.53, -6.91, -7.24, -9.90]
(slope, intercept) = my_inference_program(xs, ys, 1000)
println("slope: $slope, intercept: $intercept")
```

Gives:
```julia
julia> (slope, intercept) = my_inference_program(xs, ys, 1000)
ERROR: UndefVarError: my_model not defined
Stacktrace:
 [1] my_inference_program(::Array{Float64,1}, ::Array{Float64,1}, ::Int64) at ./none:11
 [2] top-level scope at none:1

julia>
``` 

Just a heads up on out of date documentation. 

Moving to the quickstart jupyter files.

**Comment by ztangent** [comment]
@nick-torenvliet can you point to where this documentation is located? This doesn't seem to be the code that's in our stable documentation: https://www.gen.dev/stable/getting_started/#Installation-1

The error is caused my `my_model` being undefined, because the code listing you gave only shows the model `generate_datum` being defined, and not `my_model`. The example in the docs linked above doesn't have this issue though.

To explain a little further, `my_inference_program` defines an MCMC inference algorithm specifically for the model called `my_model`, which is assumed to have already been defined. If you want to do inference over a different model, you need to make sure that when generating the initial trace, you do it from the model of interest. So if you wanted to do inference over `generate_datum` instead of `my_model`, then instead of writing:
```julia
    (trace, _) = generate(my_model, (xs,), constraints)
````
you would write:
```julia
    (trace, _) = generate(generate_datum, (xs,), constraints)
```
and make sure that `constraints` only contains observations of variables which are sampled by `generate_datum` (e.g. `:is_outlier` , or `:y`).

If you want to write a more general MCMC algorithm, you could try and rewrite `my_inference_program` so that it takes in the model you're doing inference over as an argument. But the philosophy behind Gen is that, oftentimes, it makes more sense to write a custom inference program specialized to the model you're doing inference over.

As a result, we don't provide black-box MCMC algorithms that work for all models, like those present in other probabilistic programming libraries. (Though if you did want to write such a black-box algorithm, like single-site Metropolis Hastings, it wouldn't be hard to write.)

**Comment by nick-torenvliet** [comment]
Yeah, it's on the web-site... so not official docs I guess... hold on.

In the first section, you'll find the webuser running the code as I cut and pasted it... to get the error.

https://www.gen.dev/dev/getting_started/#Installation-1
Getting Started · Gen<https://www.gen.dev/dev/getting_started/#Installation-1>
Getting Started Installation. First, obtain Julia 1.3 or later, available here.. The Gen package can be installed with the Julia package manager. From the Julia REPL ...
www.gen.dev


________________________________

**Comment by nick-torenvliet** [comment]
I'll check out the docs.

________________________________

**Comment by nick-torenvliet** [comment]
Also thanks for the help above!
