### ISSUE TITLE
`get_retval` returns references

### ISSUE THREAD

**Issue by mirkoklukas** [probcomp/Gen.jl#390]
This is more of a documentation issue: 
The objects from `get_retval` are actually references to the return values of the trace and mutating them is in fact mutating the return value of the trace.

**Comment by femtomc** [comment]
@mirkoklukas Can you be a bit more specific here? This behavior will depend on the value type of the return value.

Arrays, yes -- you're right. `isbits` types, no -- you'll get a value representation which can be freely mutated.
Dictionaries, yes -- you're right.

Because any trace is a Julia structure, it basically has to be treated as such with respect to mutation. Which means that implementing `get_retval` by accessing a field in the trace will have the same behavior as `getfield` for other structs -- that is, there's no special logic which makes traces "fully immutable" when accessing a field returns a value type which contains pointers to memory.

**Comment by mirkoklukas** [comment]
@femtomc I suggested adding a sentence to the documentation, it took me a minute to identify that the above issue caused a bug in my code. The documentation could have easily helped with that. Period. Wasn't clear to me that `get_retval` is just a lookup. It just states the obvious for people who are newish to Julia. Certainly an audience Gen wants to target. I don't need an explanation _why_ this behaviour makes sense, I know _why_, because I debugged my code.

**Comment by femtomc** [comment]
@mirkoklukas I'm not really sure what you're suggesting. You're free to open a PR in the docs?

**Comment by femtomc** [comment]
Re -- I don't view it as the responsibility of Gen to educate someone on how Julia works, inasmuch as specific Gen features may require some advanced understanding (like Julia macros, or Julia's staging mechanism).

You're free to disagree with me -- and you're also free to submit a PR for things you view should be changed.

**Comment by femtomc** [comment]
I do think your confusion as to what can be mutated from the trace is an important source of clarification, however, because the interface does state that traces are treated as immutable -- specifically here: https://www.gen.dev/dev/ref/gfi/#Updating-traces-1

One nice thing which might come out of this is a change to this description, as per your discussion above.
