### ISSUE TITLE
Gen.train not updating parameters

### ISSUE THREAD

**Issue by JGameCreation** [probcomp/Gen.jl#414]
Hi! I try to use Gen.train and wrote this very simple test code:
```
@gen function model()
    @param x_mu::Float64
    x = @trace(normal(x_mu, 1.), :x)
end
function data_generator()
    x = normal(3., 1.)
    constraints = Gen.choicemap()
    constraints[:x] = x
    return ((), constraints)
end
update = Gen.ParamUpdate(Gen.FixedStepGradientDescent(0.1), model);
init_param!(model, :x_mu, 1.0)
scores = Gen.train!(model, data_generator, update,
    num_epoch=200, epoch_size=100, num_minibatch=1, minibatch_size=100, evaluation_size=20, verbose=true);
for param in get_params(model)
    println("$param $(get_param(model, param))")
end
```
I would expect the parameter x_mu to be trained but it always remains unchanged.

**Comment by alex-lew** [comment]
@JGameCreation Sorry for the (very) late reply!

The issue here is that the `ParamUpdate` object needs to either:
* manually specify a list of parameters to train, using the explicit `param_list` argument (https://github.com/probcomp/Gen.jl/blob/44f5f1408caf05ff95932bb58d9f57907c5084e3/src/optimization.jl#L19); or
* be created after the `init_param!` call, in which case it will train all *initialized* parameters. 

In your example, switching the order of the `init_param` line and the `ParamUpdate` line fixes the issue. This is not documented, but definitely should be. I've opened another issue to track that (#455). Thanks for the report and sorry again for the months-late reply!
