### ISSUE TITLE
Impossible constraints => possible?

### ISSUE THREAD

**Issue by qiyam** [probcomp/Gen.jl#424]
Hi, I'm new to Gen, but based on what I understand, there appears to be a bug with being able to observe an impossibility. 

I stumbled onto this when I had a larger generative model not abide by the exact constraints. Is this expected?

```
@gen function test_illegal_observation()
    @trace(uniform_discrete(1, 10), :number)
end

function infer_illegal(model, amount_of_computation)
    observations = Gen.choicemap()
    observations[:number] = 11
    (trace, _) = Gen.importance_resampling(model, (), observations, amount_of_computation);
    return trace
end;
test_traces = [infer_illegal(test_illegal_observation, 10) for _=1:10];
[Gen.get_choices(trace)[:number] for trace in test_traces]

10-element Vector{Int64}:
 11
 11
 11
 11
 11
 11
 11
 11
 11
 11
```

**Comment by ztangent** [comment]
Some of Gen's inference primitives (e.g. `generate`) and built-in algorithms (e.g. `importance_resampling`) currently do not check whether an observation is impossible. However, they will return `-Inf` log weights, indicating that the trace is impossible. This is sometimes desirable: e.g., I might have a proposal distribution that sometimes proposes values outside of the support of the prior, but as long as some samples are within the support, `importance_resampling` will automatically reject the traces that correspond to the out-of-support samples because they have `-Inf` weight.

Hope this helps! There's further discussion on related issues in #391 and #379.
