### ISSUE TITLE
Docker build runs latest version of Julia instead of intended version

### ISSUE THREAD

**Issue by ztangent** [probcomp/Gen.jl#451]
[Based on this Travis log](https://app.travis-ci.com/github/probcomp/Gen.jl/jobs/560758605), it appears that the Docker build uses the latest version of Julia (1.7 as of the time of filing this issue) instead of the intended version (1.4, for the linked log). I'm not an expert on Docker, so maybe someone else more familiar could fix this?

**Comment by alex-lew** [comment]
@mugamma It looks like you were the one to commit the Travis / Docker integration. Do you remember the motivation for this (vs. whatever we were doing for, without Docker)?

I'm also not a Docker expert but my guess is the `FROM julia` line in the Dockerfile is just getting the official Julia base image, which has the latest version?

It looks like we are still running and passing tests on Travis during the `test` phase, but not the `docker` phase (https://app.travis-ci.com/github/probcomp/Gen.jl/builds/246877812). But why do we need a `docker` phase?

**Comment by mugamma** [comment]
@alex-lew as far as I remember the point was to create a Dockerfile that works and make sure that if someone created a container using `/docker/Dockerfile` they can indeed use Gen within Docker. [The previous docker file](https://github.com/probcomp/Gen.jl/blob/4827a4c2edbc17446d6e3b314f58d43d3093208b/docker/ubuntu1604) was pretty ad hoc, and if I remember correctly didn't work because it was out of date. The point was to fix it and add the `docker` phase to CI so we make sure it does not go out of date again. I also remember the PR [had no issues](https://app.travis-ci.com/github/probcomp/Gen.jl/builds/217024205) and @marcoct [merged](https://github.com/probcomp/Gen.jl/pull/376) it later.

RE solutions, the [`FROM`](https://docs.docker.com/engine/reference/builder/#from) command indeed pulls the official Julia package from Dockerhub. There are [tags](https://hub.docker.com/_/julia/) that we can use to specify which version of Julia we need to pull, but I believe 1.4 is not supported anymore. Depending on the specific dependencies you might wanna go back to something like the previous Dockerfile based on a general-purpose image such as `ubuntu` or `archlinux`, or change the Travis config file to make sure that the latest version of Julia is used in both `test` and `docker` phases.

**Comment by alex-lew** [comment]
@mugamma Thanks for the context!

Given that we no longer rely on Docker for problem sets, and no longer recommend Docker as the way to install Gen, I wonder if we can get rid of this test? Or we can use the 1.6 image (thanks for the reference to the tags!)—tests should pass on 1.6.

**Comment by ztangent** [comment]
It seems like it's still possible to specify and pull the 1.4 tag, even if it's no longer officially supported, so that might be another option? (I don't have much insight into how valuable it is to continue maintaining the Docker builds, unfortunately!)

**Comment by mugamma** [comment]
If Docker is no longer recommended then I think the most robust thing to do is to remove the test and the `/docker/` directory.
