### ISSUE TITLE
Best way to calculate expected values of a model?

### ISSUE THREAD

**Issue by blargg** [probcomp/Gen.jl#452]
Sorry if I missed this, I looked through the tutorials, and didn't find an explicit example.

I'm looking for the current best way to generate expected values for models. 
For example, if we have model x, and we want the expected value of f(x).

Right now, it seems like the best way is to integrate by generating samples of x from P(x). This should work, but should have higher variance than the alternative.

I would like to generate samples for a probability distribution proportional to |f(x)| p(x). This would reduce the variance. I Haven't figured out a way to sample over this though.

Ideally, it seems like there would be some function to take care of the whole integration for us (assuming this is common and useful to a lot of people).

**Comment by ztangent** [comment]
EDITED: Updated the code in response to Alex's correction below!

Good question! One way to do this is to use the traces generated by [importance sampling](https://www.gen.dev/dev/ref/importance/).

Suppose we have some `model` representing a distribution P(x,z), a `proposal` representing a distribution Q(z), and we want to estimate the expectation of f(z) with respect to the posterior P(z|x), where `x` is represented by a choicemap of `observations`. We can generate weighted traces of the model by running:
```julia
traces, log_norm_weights, _ = importance_sampling(model, model_args, observations, N, proposal, proposal_args)
```
where `N` is the number of samples. Here `log_norm_weights` is a vector of the log normalized importance weights. Now let's say we have some function `f` that takes in a `trace` and returns the value we care about. We can estimate the expectation of `f` by taking the weighted sum:
```julia
expectation_estimate = sum(f(tr) * exp(w) for (tr, w) in zip(traces, log_norm_weights))
```

In the case where `f` just looks up the value associated with some address `:z` in the `model`, we can also just do:
```julia
expectation_estimate = sum(tr[:z] * exp(w) for (tr, w) in zip(traces, log_norm_weights))
```

Hope this helps! Taking a weighted sum is simple enough that we haven't so far thought it was necessary to write a separate function for it, but we might in the future. The hard part is choosing the proposal distribution that's proportional to |f(x)| p(x). Right now there don't seem to be good ways of automatically constructing such proposals given arbitrary choices of f(x) and p(x), and so we leave it up to the user to choose a good proposal.

**Comment by blargg** [comment]
Thanks for the quick response.

Thanks for the help, I missed that importance_sampling let you select the distribution that values are sampled from. I'll see if I can get this working.

For selecting a distribution proportional to `|f(x)|p(x)`, one thing can do is use metropolis hastings to generate samples. We should be able to give it an arbitrary function `g :: x -> float` and use mh to generate samples proportional to that function. This can be used to calculate integrals, but I might be missing some details about how we need to weight the samples.

I couldn't find a way to give this extra information to the existing mh functions.

**Comment by alex-lew** [comment]
Hi @blargg!

It's true that the lowest-variance importance sampling estimator of E[f(x)] generates proposals not from p but from a distribution proportional to `|f(x)|p(x)`. Let's call that distribution `q`. We don't know `q`'s normalized density, only the unnormalized version. Let's write `Z_q` for the normalizing constant, `Z_q = \int |f(x)| p(x) dx`. 

We don't have a great way of generating samples from `q` in general, but as you say, we could use MCMC. The problem is, as you suspected, the weighting. Even if we did have samples from `q`, the importance sampling estimator of E[f(x)] would be `f(x) * p(x) / q(x)` (for `x ~ q`), and we don't know `q`'s density: we only know `|f(x)| * p(x)  = Z_q * q(x)`, and we don't know `Z_q`.

We could try to estimate `Z_q`, itself an integral, using another layer of importance sampling, with some proposal distribution `h(x)` designed to approximate `q`; then our estimate would become  `Z_q * f(x) * p(x) / (|f(x)|p(x)) = sign(f(x)) * Z_q`. (Note that this depends only on the sign of `f(x)`, not the value.) But the variance of this estimator will depend on how closely `h` approximates `q`. If you're going to go through the trouble of designing an `h` that approximates `q` closely, you could use it directly to compute the expectation you're interested in: `E_p[f(x)] = E_h[f(x) * p(x)/h(x)]`.

Coming back to Gen: you can implement this strategy by writing a generative function `h` designed to approximate `q(x) \propto |f(x)| p(x)`, and then using it as an importance sampling proposal (as in @ztangent's answer).

Gen does also support MH, so if you do want to use MCMC, I'm happy to give some pointers! For example, you might use MH to draw samples from `q`, then use those samples to learn an approximation `h` that you can use within importance sampling. (The "learning" could be based on neural networks, or something simpler, like a Gaussian mixture fit to the samples.)

If you can say a bit more about your use case, we may be able to give additional pointers. In many settings, the 'pure Monte Carlo estimator' (generating samples from `p` and averaging `f(x)` across the samples) will be a sufficiently low-variance estimator. The times when it isn't are when `|f(x)| * p(x)` is very different from `p`, i.e., when high-|f(x)| values are rare under `p`. In this case you're really trying to do 'rare event simulation'; Gen should help to implement several rare event simulation method (e.g., the ones that rely on MCMC can use Gen's MCMC features), but we don't yet have a special library for rare event simulation with Gen. (I think it would be great to have one, though!)

**Comment by alex-lew** [comment]
> Here `log_norm_weights` is a vector of the log normalized importance weights. Now let's say we have some function `f` that takes in a `trace` and returns the value we care about. We can estimate the expectation of `f` by taking the weighted sum:
> 
> ```julia
> expectation_estimate = sum(f(tr) * w for (tr, w) in zip(traces, log_norm_weights))
> ```

(Note that the weighted sum should be weighted by the non-log-space weights, so `f(tr) * exp(w)`, rather than `f(tr) * w`.)

**Comment by blargg** [comment]
Thanks, both of you, for the wonderful help.

So you are right about MH. Normalization is difficult enough that there's no real efficient way to account for it. I'm used to using Metropolis Light Transport, where we do use MH to evaluate an integral of a function `f(x)`, but it seems like we can just fudge the normalization factor at the end, somehow. After all, most of the information is in the relative pixel values, and normalization should just be the brightness of the final image (though, this explanation might be wrong).

I don't think I can do the same trick for what I'm currently working on, so importance sampling is the way to go.

I think I have an example of importance sampling working. Just to check, `proposal` is a generative function that just needs to assign the variables from whatever distribution you think is important, right?

So for a simple function with no inference:
```
@gen function model()
	x ~ normal(3,1)
	y ~ normal(2,3)
	return x + y
end
```

I can use the proposal function:
```
@gen function proposal()
	x ~ normal(3, 0.1)
	y ~ normal(2, 0.1)
end
```

To sample x and y more tightly around their means.

**Comment by ztangent** [comment]
> Just to check, proposal is a generative function that just needs to assign the variables from whatever distribution you think is important, right?

Yes, that's right! And the example you gave checks out :)

**Comment by blargg** [comment]
Alright, thanks for the help!

**Comment by RoyiAvital** [comment]
Wouldn't such discussion be better located at Discussions? You may enable discussions for this repository.
