### ISSUE TITLE
Delta distributions

### ISSUE THREAD

**Issue by nathanielvirgo** [probcomp/Gen.jl#458]
I'm just starting out with Gen, so apologies if this is a silly question, but it seems to me that it would sometimes be useful to have delta functions, e.g.

```julia
A = {:A} ~ bernoulli(0.5)
B = {:B} ~ delta(A)
```

Of course this would be operationally the same as

```julia
A = {:A} ~ bernoulli(0.5)
B = A
```

but the difference is that `:B` would appear in the trace and could even be forced to be not equal to A using a choicemap. I can see possible uses for this.

I had a go at trying to implement `delta` myself using `@gen` or `@dist`, but I wasn't successful, in that I couldn't see a way to do it. Is there a way that delta functions can be implemented, and/or would it be possible to add them as a built-in distribution?

**Comment by alex-lew** [comment]
Hi @nathanielvirgo! Thanks for trying out Gen, and for the suggestion!

One way to get this behavior using `@dist` is 

```
@dist delta(x) = fill(x, 1)[uniform_discrete(1, 1)]
```

As you mention, using `delta` has two consequences:

* It 'saves' the value in the trace. If all you care about is easy access to a value from a trace, you can also use `@gen save(x) = x`. If you then do `{:val} ~ save("hello")`, you will be able to get the value out of a trace using `trace[:val]`, even though `:val` is not considered a random choice (it cannot be constrained, and will not show up as part of the pretty-printed choice map). This is because, for convenience, traces allow easy access to the return values of any generative function calls you make.
* It makes it possible to constrain the choice. However, since Gen can't invert arbitrary deterministic logic in your program, some inference methods won't work when you do this. For example, if you try to make a Metropolis-Hastings update to `:A` in your example, or to `:B`, the updates will always be rejected, because they move the trace into an invalid state (where `A` and `B` are not the same). You need to propose changing them both at once. As long as you keep this in mind and adjust your inference method accordingly, though, there shouldn't be any problems.

Another note: Gen's mathematical underpinnings (see, e.g., [Marco's thesis](https://www.mct.dev/assets/mct-thesis.pdf)) do not support `delta` applied to continuous variables. For example, consider:

```
# This generative function breaks assumptions that Gen makes
@gen function f()
  x ~ normal(0, 1)
  y ~ delta(2 * x)
end
```

The first problem is that none of the 'generic' inference methods will ever 'guess' the exact right `x` for an observed `y`. But even if you provide a custom proposal that inverts the logic manually (e.g., `@gen proposal(y) = x ~ delta(y/2)`), the importance weights Gen computes will be off. (For example, the average importance weight when `y` is constrained *should* be the marginal density of `y`, but Gen will give the marginal density of `x`.) It is possible to resolve this issue, and we have ongoing research on the topic :) But because, at the moment, there are many ways to break Gen's assumptions using `delta`, we haven't included it as a default distribution. If it's useful for your use case, and doesn't break anything, feel free to use the one-liner above!
