### ISSUE TITLE
Design: should a trace store the observation values used in initialize?

### ISSUE THREAD

**Issue by fsaad** [probcomp/Gen.jl#47]
Consider the following:
```julia
    xs = ...
    ys = ...
    observations = Gen.DynamicAssignment()
    for (i, y) in enumerate(ys)
        observations[(:y, i)] = y
    end
    (trace, _) = Gen.initialize(model, (xs,), observations)
```
It seems sensible that the execution trace should store the observations (or perhaps only the addresses) that were constrained upon generation of the trace.

This information could simplify the somewhat awkward design of `Gen.importance_sampling`:
```julia
function importance_sampling(model::GenerativeFunction{T,U}, model_args::Tuple,
                             observations::Assignment,
                             num_samples::Int) where {T,U}
```
which (like `black_box_vi!`) requires the actual `observations` to be passed in, as opposed to a `selection::AdressSet` which is taken by `metropolis_hastings`, `hmc`, `map_optimize`, `mala`. By storing the observations in the trace we could in principle remove make the inference workflow be of a more standard form:
1. Define observations.
2. Obtain trace using Gen.initialize(model, (args,), observations), with the observations being stored in the trace.
3. Run inference operators on `selection:AddressSet`.

**Comment by alex-lew** [comment]
My instinct is to say that it's totally fine for `importance_sampling` to take in observations but for `mh`, `mala`, etc. not to. `mh` and `mala` are building blocks that make a single-step update to a trace. `importance_resampling` is an entire inference algorithm, and has no use for an "initial trace."

Also worth noting that there are three versions of `mh` in the standard library, and two of them do not accept a `selection::AddressSet`, but rather a custom proposal. I think it'd be hard to come up with a unified signature for inference library functions (and not necessarily desirable).

**Comment by fsaad** [comment]
> `importance_sampling" is an entire inference algorithm and has no use for an "initial trace.

But why treat importance sampling in this monolithic way?

Importance resampling can be applied to a subset of addresses in an
existing trace; it can be applied compositionally, sequentially, etc.,
as a single-step update to a trace; and it can be interspersed with
other types of inferences. The combination of specifying a "model +
observations" in the existing signature is already, in effect,
specifying an initial trace fragment...

I can imagine a less monolothic implementation of importance sampling
that takes in a trace and a set of addresses (and optionally a
proposal). Provided that the trace stores a reference to the
underlying GenerativeFunction that it traces (which appears to be the
case at least for DynamicDSLTrace) the existing four algorithms in
importance.lj can be recovered in a straightforward way.

Advantages of the proposed approach would be that importance sampling
can be applied traces that came from anywhere as opposed to the more
restrictive "model + observations" interface. There are probably
disadvantages of this approach with respect to the Gen implementation
that Marco can shed light on.

**Comment by marcoct** [comment]
> By storing the observations in the trace we could in principle remove make the inference workflow be of a more standard form..

I think that we should expect that different functions in the standard inference library have different type signatures. I don't think that expecting all inference library methods to have the same type signature makes sense, because different inference methods simply require different pieces of data, and introducing uniformity into the inference library amounts to introducing artificial constraints. Forcing the importance sampling implementation to start with an initial trace, when only the observed part of the trace is actually used, is an example of this. In this case, I imagine that users would be confused about what importance sampling is actually doing with the initial trace, while the current design makes it explicit that importance sampling just requires the observations and does not use the latent variables.

> Importance resampling can be applied to a subset of addresses in an
existing trace; it can be applied compositionally, sequentially, etc.,
as a single-step update to a trace; and it can be interspersed with
other types of inferences.

In principle the standard inference library could be extended with a version of importance sampling that takes as input an initial trace and a selection that together define the observations. However, I'm not sure why this would be useful, because importance sampling will presumably be not using the latent state in the trace (so why would it be generated in the first place?).

I could imagine a useful inference library method that is not importance sampling but has a similar type signature to the suggested function -- an implementation of an MCMC update (which is a special instance of particle Gibbs) that takes as input (i) an input trace, (ii) a selection indicating the subset of (latent) variables to be re simulated, (iii) a number of simulations (N) to do. The function would generate N new traces using `free_update` starting from the provided input trace, and resimulating the selected choices, and then use the weights for each to resample one, which is returned. This would be an MCMC kernel, though (which indeed uses all the information in the input trace), and not importance sampling.

**Comment by fsaad** [comment]
> However, I'm not sure why this would be useful, because importance sampling will presumably be not using the latent state in the trace (so why would it be generated in the first place?).

I personally think the proposal useful because I find an interface of the form:

```julia
function importance_resampling(
    trace,
    selection::AddressSet,
    proposal::GenerativeFunction{V,W},
    proposal_args::Tuple,
    num_samples::Int)
end
```

to be an improvement to the current form

```julia
function importance_resampling(
    model::GenerativeFunction{T,U},
    model_args::Tuple,
    observations::Assignment,
    proposal::GenerativeFunction{V,W},
    proposal_args::Tuple,
    num_samples::Int)
end
```

in the sense that the first one is more general: it can be applied to any *trace*, regardless of where it came from, whereas the second must be applied to a particular model function and observations.

For instance, using the first signature, a user can first obtain a trace using MCMC inference and then run a final IS step on that trace, which is not possible with the existing version (the user would have to pull out the "observations" from the MCMC-obtained trace and then call IS). Also, the first signature allows one to more easily implement something like SIS in user-space.

From a design and pedagogical perspective, I happen to think that the "trace + address selection" is aesthetically less clunky than "model + arguments + observations" and more in line with the idea of probabilistic programming with first class traces.

**Comment by marcoct** [comment]
> For instance, using the first signature, a user can first obtain a trace using MCMC inference and then run a final IS step on that trace

What do you mean by "run an IS step on a trace"?

**Comment by fsaad** [comment]
> What do you mean by "run an IS step on a trace"?

Here is the simplest version of the workflow I am imagining:

1. Generative model *x* -> *y* -> *z*.
2. Suppose that *z* is "observed data".
3. User runs maximum likelihood optimization to obtain estimate *y'* = argmax{p(*z*|*y*)}.
4. User runs importance resampling to obtain a sample *x'* ~ p(*x*|*y'*).

If maximum likelihood takes a trace + selection and returns a trace, and importance resampling takes a trace + selection and returns a trace, then the inference workflow is compositional with a relatively consistent interface.

**Comment by marcoct** [comment]
The built-in inference library is designed to capture common patterns, and users are free and expected to write code that combines use of multiple inference library functions and/or generative function interface methods to implement that type of non-canonical inference algorithm (note that there is large room for customization of inference within use of the inference library itself through e.g. custom proposals and custom MH moves).

Sequential importance sampling and more general sequential Monte Carlo schemes will be supported by the inference library (e.g. the particle filter functionality currently in the library suffices for a broad set of sequential importance sampling-based algorithms). It sounds like `particle_filter` is an algorithm template that captures the sequential nature of what @fsaad is proposing (i.e. taking a trace, extending it,and getting an importance weight), although the combination of maximum likelihood and importance sampling into a unique hybrid that cannot be  interpreted as an instance of sequential importance sampling is not something that I anticipate we want in the standard library, until we see several examples of this being used. Even then, it might be better suited to a domain-specific inference library.

I can see why storing the observations that were used to initialize the trace is appealing -- it could conceivably allow methods to distinguish between observations and non-observations for the lifetime of the trace. For example, MCMC methods could throw an error if those addresses were changed. However, this also makes the concept of a trace significantly more complex, and higher-level than it currently is. Traces are intended to be low-level data structures that just represent executions of generative code with minimally complex semantics -- which addresses have the role of observations vs the role of latents is something that doesn't belong at this level. I had previously considered creating a separate (higher-level) notion of "conditioned model", which combines a generative function for the model, with a choice map for the observations, and we may still want to add that in later, but it is a separate concept from a trace. I think it's helpful to keep the low-level abstractions particularly simple, and not to be afraid of introducing more layers of abstraction instead of pushing things into the lower layers.
